#+TITLE: hybridizer_python
#+AUTHOR: Peter Polidoro
#+EMAIL: peterpolidoro@gmail.com

* Package Information
  - Name :: hybridizer_python
  - Version :: 1.17
  - License :: BSD
  - URL :: https://github.com/janelia-pypi/hybridizer_python
  - Author :: Peter Polidoro
  - Email :: peterpolidoro@gmail.com

  This Python package (hybridizer) creates a class named Hybridizer to
  communcate with and control the Janelia Hybridizer. The hybridizer
  uses two hardware control devices, the mixed_signal_controller
  modular_device, and the bioshake_device. The
  mixed_signal_controller both switches the valves and reads the
  analog signals from the cylinder hall effect sensors. The
  bioshake_device controls the heater/shaker.

* Example Usage

  [[./example_config.yaml]]

  Open a terminal and enter:

  #+BEGIN_SRC sh
    source ~/virtualenvs/hybridizer/bin/activate
    cd ~/git/hybridizer_python
    ipython
  #+END_SRC

  In iPython enter:

  #+BEGIN_SRC python
    from hybridizer import Hybridizer
    hyb = Hybridizer('example_config.yaml')
    hyb.run_protocol()
  #+END_SRC

* Installation

  [[https://github.com/janelia-pypi/python_setup]]

*** Debian-based Linux Install Dependencies

    Open a terminal and enter:

    #+BEGIN_SRC sh
      sudo apt-get install git python-virtualenv -y
    #+END_SRC

** Linux and Mac OS X

   Open a terminal and enter:

   #+BEGIN_SRC sh
     mkdir ~/git
     cd ~/git
     git clone https://github.com/janelia-pypi/hybridizer_python.git
     cd hybridizer_python
     git checkout --track origin/digital
     mkdir -p ~/virtualenvs/hybridizer
     virtualenv ~/virtualenvs/hybridizer
     source ~/virtualenvs/hybridizer/bin/activate
     pip install ipython modular_device bioshake_device pyyaml
   #+END_SRC

   On linux, you may need to add yourself to the group 'dialout' in order
   to have write permissions on the USB port:

   Open a terminal and enter:

   #+BEGIN_SRC sh
     sudo usermod -aG dialout $USER
     sudo reboot
   #+END_SRC

** Windows

   Open a terminal and enter:

   #+BEGIN_SRC sh
     virtualenv C:\virtualenvs\hybridizer
     C:\virtualenvs\hybridizer\Scripts\activate
     pip install ipython
     pip install modular_device
     pip install bioshake_device
     pip install pyyaml
   #+END_SRC
